// Admin "install as app" check: manifest, service worker, Chrome installability, top-bar layout on a small phone
import { chromium } from 'playwright'
const B = 'http://127.0.0.1:4000', out = []
const br = await chromium.launch()
const ctx = await br.newContext({ viewport: { width: 360, height: 760 } })
const p = await ctx.newPage()
const errs = []; p.on('pageerror', e => errs.push(String(e)))
await p.goto(B + '/admin.html?emu')
await p.waitForFunction(() => navigator.serviceWorker && navigator.serviceWorker.controller, null, { timeout: 15000 }).catch(() => {})
if (!(await p.evaluate(() => !!navigator.serviceWorker.controller))) { await p.reload(); await p.waitForTimeout(2000) }
out.push('SW controller: ' + await p.evaluate(() => navigator.serviceWorker.controller && navigator.serviceWorker.controller.scriptURL))
out.push('SW scope: ' + await p.evaluate(async () => (await navigator.serviceWorker.getRegistration('/admin.html'))?.scope))
const cdp = await ctx.newCDPSession(p)
const m = await cdp.send('Page.getAppManifest').catch(e => ({ err: String(e) }))
out.push('Manifest url: ' + m.url + ' | parse errors: ' + JSON.stringify(m.errors || m.err))
const ie = await cdp.send('Page.getInstallabilityErrors').catch(e => ({ err: String(e) }))
out.push('Installability errors: ' + JSON.stringify(ie.installabilityErrors ?? ie.err))
for (const u of ['/admin-icon-192.png', '/admin-icon-512.png', '/admin-icon-maskable-512.png', '/admin-apple-touch-icon.png', '/admin-manifest.json'])
  out.push(u + ' ' + (await p.request.get(B + u)).status())
out.push('login install btn visible: ' + await p.locator('.inst').first().isVisible())
await p.screenshot({ path: 'shots/install-login.png' })
await p.fill('#le', 'deependrasinghbaghel30@gmail.com'); await p.fill('#lp', 'Super@12345'); await p.click('#lb')
await p.locator('.top').waitFor({ timeout: 20000 }).catch(() => {})
await p.click('.top .inst'); await p.waitForTimeout(400)
out.push('help sheet shown: ' + await p.locator('#ihelp').isVisible() + ' | ' + ((await p.locator('#ihelp').textContent().catch(()=>''))||'').slice(0,90))
await p.screenshot({ path: 'shots/install-help.png' })
await p.click('#ihok'); out.push('help closed: ' + !(await p.locator('#ihelp').count()))
const top = await p.evaluate(() => { const t = document.querySelector('.top'); return t ? { h: t.offsetHeight, sw: t.scrollWidth, cw: t.clientWidth } : null })
out.push('top bar @360: ' + JSON.stringify(top))
await p.screenshot({ path: 'shots/install-top.png' })
// offline page
await ctx.setOffline(true)
await p.goto(B + '/admin.html').catch(e => out.push('offline nav err ' + e.message))
out.push('offline page text: ' + (await p.textContent('body').catch(() => '')).replace(/\s+/g, ' ').slice(0, 80))
await ctx.setOffline(false)
out.push('JS errors: ' + JSON.stringify(errs))
await br.close()
console.log('INSTALL CHECK:\n' + out.join('\n'))
